mod_name=Dynamic Trees Terralith
mod_id=dtterralith
mod_version=1.4.0-BETA1
mod_group_id=maxhyper.dtterralith
modrinthId=dynamic-trees-terralith
mod_license=MIT
mod_authors=DJS, Max Hyper
mod_credits=m3t4f1v3
mod_description=Adds Dynamic Trees Compatibility with Terralith.

java_version=25
minecraft_version=26.2
fabric_loader_version=0.19.3
fabric_version=0.155.2+26.2

dynamic_trees_version=1.8.0-BETA03
forge_config_api_port_version=26.2.1

org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
