modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="dtterralith"
version="${file.jarVersion}"
displayName="Dynamic Trees for Terralith"
credits=""
authors="DJS, Max Hyper"
description='''
Adds Dynamic Trees Compatibility to Terralith. 
'''

[[dependencies.dtterralith]] #optional
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtterralith]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtterralith]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.1.0-BETA3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtterralith]]
    modId="dynamictreesplus"
    mandatory=false
    versionRange="[1.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtterralith]]
    modId="terralith"
    mandatory=true
    versionRange="[2.3.10,)"
    ordering="AFTER"
    side="BOTH"

